- name: Install netcat for statsd
  become: yes
  apt:
    pkg:
    - netcat
- name: Download netdata script
  register: netdata_download
  get_url:
    url: "https://my-netdata.io/kickstart.sh"
    dest: /tmp/get_netdata.sh
    mode: '0755'
- name: Run netdata script
  when: netdata_download.changed
  become: yes
  shell: /tmp/get_netdata.sh --stable-channel --disable-telemetry
- name: Template netdata.conf
  become: yes
  register: netdata_file
  failed_when: false
  copy:
    src: netdata.conf
    dest: /etc/netdata/netdata.conf
    owner: root
    group: root
    mode: '0644'
- name: Template netdata.conf (if failed to template first time)
  become: yes
  register: netdata_file_2
  when: netdata_file.failed
  copy:
    src: netdata.conf
    dest: /opt/netdata/etc/netdata/netdata.conf
    owner: root
    group: root
    mode: '0644'
- name: Restart netdata
  become: yes
  when: netdata_file.changed or netdata_file_2.changed
  systemd:
    name: netdata
    state: restarted
