version: "3.9"
services:
  bind9:
    image: ubuntu/bind9:9.16-20.04_beta
    ports:
      - "53:53/udp"
    environment:
      TZ: "America/Chicago"
      BIND9_USER: root
    volumes:
      - '/home/ansible/.ansible/docker/compose/router/bind:/etc/bind'
    networks:
      router_net:
        ipv4_address: 10.0.1.2
    restart: unless-stopped
  dhcpd-v4-eth1:
    image: networkboot/dhcpd:latest
    network_mode: host
    volumes:
      - '/home/ansible/.ansible/docker/compose/router/dhcpd-v4-eth1/dhcpd.conf:/data/dhcpd.conf'
    command: eth1
    restart: unless-stopped
  dhcpd-v6-eth1:
    image: networkboot/dhcpd:latest
    network_mode: host
    environment:
      DHCPD_PROTOCOL: 6
    volumes:
      - '/home/ansible/.ansible/docker/compose/router/dhcpd-v6-eth1/dhcpd.conf:/data/dhcpd.conf'
    command: eth1
    restart: unless-stopped
  radvd-eth1:
    image: rsrchboy/radvd
    network_mode: host
    volumes:
      - '/home/ansible/.ansible/docker/compose/router/radvd-eth1/radvd.conf:/etc/radvd.conf'
    command: -d 2 -m stderr
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  autoheal:
    image: willfarrell/autoheal:latest
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
  ddns-updater:
    image: qmcgaw/ddns-updater:latest
    volumes:
      - '/home/ansible/.ansible/docker/compose/router/dns-updater/config.json:/updater/data/config.json'
      - '/home/ansible/.ansible/docker/compose/router/dns-updater/updates.json:/updater/data/updates.json'
    restart: unless-stopped
  ipsec-vpn-server:
    image: hwdsl2/ipsec-vpn-server:latest
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/ppp:/dev/ppp"
    volumes:
      - "ikev2-vpn-data:/etc/ipsec.d"
    environment:
      VPN_DNS_SRV1: 10.0.1.2
      VPN_DNS_SRV2: 8.8.8.8
      VPN_IKEV2_ONLY: "yes"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.send_redirects=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.accept_redirects=0
      - net.ipv4.conf.default.send_redirects=0
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.eth0.send_redirects=0
      - net.ipv4.conf.eth0.rp_filter=0
    networks:
      router_net:
        ipv4_address: 10.0.1.3
    restart: unless-stopped
volumes:
  ikev2-vpn-data:
networks:
  router_net:
    driver_opts:
      com.docker.network.bridge.name: compose1
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
