global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'netdata_all_hosts'
    metrics_path: '/api/v1/allmetrics'
    params:
      format: [ prometheus ]
    honor_labels: true
    static_configs:
      - targets: 
{% for host, info in hostvars.items() %}
        - "{{ host }}:19999"
{% endfor %}
