version: "3.9"
services:
  traefik:
    image: traefik:v2.5
    restart: always
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/ansible/.ansible/docker/compose/ironman/traefik.yml:/etc/traefik/traefik.yml"
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - "/mnt/general/transmission-data:/data"
    env_file: ./secrets.env
    restart: always
    logging:
      driver: json-file
      options:
          max-size: 10m
    labels:
      - traefik.http.routers.transmission.rule=Host(`transmission.christianbingman.com`)
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.service=transmission
    expose:
      - '9091'
    image: haugene/transmission-openvpn
  autoheal:
    image: willfarrell/autoheal:latest
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
