version: "3.9"
services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - "/mnt/general/transmission-data:/data"
    env_file: ./secrets.env
    logging:
      driver: json-file
      options:
          max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn
