## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ .Name }}.christianbingman.com`)"

metrics:
  prometheus: {}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: "christianbingman@gmail.com"
      storage: "./acme.json"
      httpChallenge:
        entrypoint: web

# API and dashboard configuration
api:
  insecure: true
