## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ .Name }}.christianbingman.com`)"

entryPoints:
  web:
    address: ":80"

# API and dashboard configuration
api:
  insecure: true
