services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  autoheal:
    image: willfarrell/autoheal:latest
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
volumes:
  homebridge:
networks:
  compose1:
    driver_opts:
      com.docker.network.bridge.name: compose1
