- name: Ansible tasks
  become_user: root
  block:
  - name: Install repo update packages
    apt:
      update_cache: yes
      pkg:
      - software-properties-common
      - apt-transport-https
      - wget
      - ca-certificates
      - gnupg2
      - git
      - acl
      - zsh
      - pass
  - name: Add neovim apt repo
    # Ignore failed, just install from default repo in this case
    failed_when: false
    apt_repository:
      repo: ppa:neovim-ppa/unstable
      codename: jammy
  - name: Install packages
    apt:
      update_cache: yes
      pkg:
      - neovim
- name: Download nix package manager installer
  get_url: 
    url: "https://nixos.org/nix/install"
    dest: /home/christian/.ansible/nix-install.sh
    mode: '0700'
- name: Install nix package manager
  shell:
    cmd: /home/christian/.ansible/nix-install.sh
    creates: "/nix"
- name: Install direnv
  shell: 
    cmd: /home/christian/.nix-profile/bin/nix-env -i direnv
    creates: /home/christian/.nix-profile/bin/direnv
- name: Check if OMZ is installed
  stat:
    path: ~/.oh-my-zsh
  register: omzfolder
- name: Download OMZ
  register: downloadOMZ
  when: not omzfolder.stat.exists
  get_url: 
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh 
    dest: /home/christian/.ansible/install.sh
    mode: '0700'
- name: Install OMZ
  when: downloadOMZ.changed
  shell: echo "n" | /home/christian/.ansible/install.sh
- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/christian/.oh-my-zsh/custom/themes/powerlevel10k
- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest:  /home/christian/.oh-my-zsh/custom/plugins/zsh-autosuggestions
- name: Install zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/christian/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
- name: Set ZSH Shell
  become_user: root
  user:
    name: christian
    shell: /bin/zsh
- name: Clone bare repo
  git:
    repo: https://github.com/christianbingman/dotfiles.git
    dest: /home/christian/dotfiles
    bare: yes
- name: Checkout bare repo
  changed_when: false
  shell: "/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME checkout -f"
- name: Don't show untracked files
  changed_when: false
  shell: "/usr/bin/git --git-dir=$HOME/dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no"
- name: Create nvim autoload directory if it does not exist
  file:
    path: /home/christian/.local/share/nvim/site/autoload/
    state: directory
    mode: '0755'
    recurse: yes
- name: Install VIM Plug for neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/christian/.local/share/nvim/site/autoload/plug.vim
